### PR TITLE
ida: added highlight_basic_blocks.py script

### PR DESCRIPTION
**Pull request by adrianherrera**
Colors basic blocks from s2e-env's basic_block_coverage subcommand.

### CODE REVIEW

**Comment by vitalych** [comment]
wouldn't it better to have this script in s2e-env, along with all the other python-based analysis tools?

**Comment by adrianherrera** [comment]
I don't think so, because this script (and the other IDA Pro scripts) are not invoked by s2e-env. It get's run by IDA Pro, and I think the distinction is important to prevent s2e-env from becoming bloated with code that is not really related to it.

I will have a look at the other scripts in the tools repo.

**Comment by vitalych** [comment]
At the same time, we already have s2e print_coverage and will very likely have s2e analyze {forkprofile, tace...], etc. So adding s2e ida highlight_coverage doesn't seems bad to me. I think we should keep the number of repos in check, they've been multiplying like rabbits so far :)

I would also like to get rid of the old tools folder and just have revgen in it.

**Comment by adrianherrera** [comment]
That's true. TBH I felt a bit conflicted about having these coverage commands and things in s2e-env, because I felt it was already starting to bloat a bit more from what I envisaged when I started it.

I guess I'll just close this PR and start working on moving things across.

**Comment by vitalych** [comment]
We'll need to switch to mcsema eventually. That will make all these ad-hoc scripts redundant.

**Pull request merged**
